#!/bin/sh
LIB_ARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)
if [ -e /usr/lib/${LIB_ARCH}/libeatmydata.so ]; then
    [ -n "${LD_PRELOAD}" ] && LD_PRELOAD="$LD_PRELOAD:"
    LD_PRELOAD="$LD_PRELOAD$so"
fi
for so in /usr/lib/${LIB_ARCH}/libeatmydata.so; do
    [ -n "$LD_PRELOAD" ] && LD_PRELOAD="$LD_PRELOAD:"
    LD_PRELOAD="$LD_PRELOAD$so"
done
export LD_PRELOAD
exec $LD_PRELOAD "$0.eatmydata" --force-unsafe-io "$@"
